vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profile_file:
            uri_prefix: /uploads/pictures/profile
            upload_destination: '%kernel.project_dir%/public/uploads/pictures/profile/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
